// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osd.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import multiraftbase "github.com/journeymidnight/nentropy/osd/multiraftbase"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SyncMapType int32

const (
	// CONSISTENT reads are guaranteed to read committed data; the
	// mechanism relies on clocks to determine lease expirations.
	PGMAP SyncMapType = 0
	// CONSENSUS requires that reads must achieve consensus. This is a
	// stronger guarantee of consistency than CONSISTENT.
	//
	// TODO(spencer): current unimplemented.
	OSDMAP SyncMapType = 1
	// INCONSISTENT reads return the latest available, committed values.
	// They are more efficient, but may read stale values as pending
	// intents are ignored.
	POOLMAP SyncMapType = 2
)

var SyncMapType_name = map[int32]string{
	0: "PGMAP",
	1: "OSDMAP",
	2: "POOLMAP",
}
var SyncMapType_value = map[string]int32{
	"PGMAP":   0,
	"OSDMAP":  1,
	"POOLMAP": 2,
}

func (x SyncMapType) String() string {
	return proto.EnumName(SyncMapType_name, int32(x))
}
func (SyncMapType) EnumDescriptor() ([]byte, []int) { return fileDescriptorOsd, []int{0} }

type UnionMap struct {
	Pgmap   *PgMaps  `protobuf:"bytes,1,opt,name=pgmap" json:"pgmap,omitempty"`
	Poolmap *PoolMap `protobuf:"bytes,2,opt,name=poolmap" json:"poolmap,omitempty"`
	Osdmap  *OsdMap  `protobuf:"bytes,3,opt,name=osdmap" json:"osdmap,omitempty"`
}

func (m *UnionMap) Reset()                    { *m = UnionMap{} }
func (m *UnionMap) String() string            { return proto.CompactTextString(m) }
func (*UnionMap) ProtoMessage()               {}
func (*UnionMap) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{0} }

func (m *UnionMap) GetPgmap() *PgMaps {
	if m != nil {
		return m.Pgmap
	}
	return nil
}

func (m *UnionMap) GetPoolmap() *PoolMap {
	if m != nil {
		return m.Poolmap
	}
	return nil
}

func (m *UnionMap) GetOsdmap() *OsdMap {
	if m != nil {
		return m.Osdmap
	}
	return nil
}

type SyncMapRequest struct {
	MapType  SyncMapType `protobuf:"varint,1,opt,name=map_type,json=mapType,proto3,enum=protos.SyncMapType" json:"map_type,omitempty"`
	UnionMap UnionMap    `protobuf:"bytes,2,opt,name=union_map,json=unionMap" json:"union_map"`
}

func (m *SyncMapRequest) Reset()                    { *m = SyncMapRequest{} }
func (m *SyncMapRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncMapRequest) ProtoMessage()               {}
func (*SyncMapRequest) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{1} }

func (m *SyncMapRequest) GetMapType() SyncMapType {
	if m != nil {
		return m.MapType
	}
	return PGMAP
}

func (m *SyncMapRequest) GetUnionMap() UnionMap {
	if m != nil {
		return m.UnionMap
	}
	return UnionMap{}
}

type SyncMapReply struct {
	RetCode int32 `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
}

func (m *SyncMapReply) Reset()                    { *m = SyncMapReply{} }
func (m *SyncMapReply) String() string            { return proto.CompactTextString(m) }
func (*SyncMapReply) ProtoMessage()               {}
func (*SyncMapReply) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{2} }

func (m *SyncMapReply) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type MigrateGetRequest struct {
	ParentPgId string `protobuf:"bytes,1,opt,name=parent_pg_id,json=parentPgId,proto3" json:"parent_pg_id,omitempty"`
	ChildPgId  string `protobuf:"bytes,2,opt,name=child_pg_id,json=childPgId,proto3" json:"child_pg_id,omitempty"`
	Marker     []byte `protobuf:"bytes,3,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (m *MigrateGetRequest) Reset()                    { *m = MigrateGetRequest{} }
func (m *MigrateGetRequest) String() string            { return proto.CompactTextString(m) }
func (*MigrateGetRequest) ProtoMessage()               {}
func (*MigrateGetRequest) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{3} }

func (m *MigrateGetRequest) GetParentPgId() string {
	if m != nil {
		return m.ParentPgId
	}
	return ""
}

func (m *MigrateGetRequest) GetChildPgId() string {
	if m != nil {
		return m.ChildPgId
	}
	return ""
}

func (m *MigrateGetRequest) GetMarker() []byte {
	if m != nil {
		return m.Marker
	}
	return nil
}

type MigrateGetReply struct {
	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Marker []byte `protobuf:"bytes,3,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (m *MigrateGetReply) Reset()                    { *m = MigrateGetReply{} }
func (m *MigrateGetReply) String() string            { return proto.CompactTextString(m) }
func (*MigrateGetReply) ProtoMessage()               {}
func (*MigrateGetReply) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{4} }

func (m *MigrateGetReply) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MigrateGetReply) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MigrateGetReply) GetMarker() []byte {
	if m != nil {
		return m.Marker
	}
	return nil
}

type CreatePgRequest struct {
	PgName          string                         `protobuf:"bytes,1,opt,name=pg_name,json=pgName,proto3" json:"pg_name,omitempty"`
	GroupDescriptor *multiraftbase.GroupDescriptor `protobuf:"bytes,2,opt,name=group_descriptor,json=groupDescriptor" json:"group_descriptor,omitempty"`
}

func (m *CreatePgRequest) Reset()                    { *m = CreatePgRequest{} }
func (m *CreatePgRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePgRequest) ProtoMessage()               {}
func (*CreatePgRequest) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{5} }

func (m *CreatePgRequest) GetPgName() string {
	if m != nil {
		return m.PgName
	}
	return ""
}

func (m *CreatePgRequest) GetGroupDescriptor() *multiraftbase.GroupDescriptor {
	if m != nil {
		return m.GroupDescriptor
	}
	return nil
}

type CreatePgReply struct {
	RetCode int32 `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
}

func (m *CreatePgReply) Reset()                    { *m = CreatePgReply{} }
func (m *CreatePgReply) String() string            { return proto.CompactTextString(m) }
func (*CreatePgReply) ProtoMessage()               {}
func (*CreatePgReply) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{6} }

func (m *CreatePgReply) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type DeletePgRequest struct {
	PgName string `protobuf:"bytes,1,opt,name=pg_name,json=pgName,proto3" json:"pg_name,omitempty"`
}

func (m *DeletePgRequest) Reset()                    { *m = DeletePgRequest{} }
func (m *DeletePgRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePgRequest) ProtoMessage()               {}
func (*DeletePgRequest) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{7} }

func (m *DeletePgRequest) GetPgName() string {
	if m != nil {
		return m.PgName
	}
	return ""
}

type DeletePgReply struct {
	RetCode int32 `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
}

func (m *DeletePgReply) Reset()                    { *m = DeletePgReply{} }
func (m *DeletePgReply) String() string            { return proto.CompactTextString(m) }
func (*DeletePgReply) ProtoMessage()               {}
func (*DeletePgReply) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{8} }

func (m *DeletePgReply) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*UnionMap)(nil), "protos.UnionMap")
	proto.RegisterType((*SyncMapRequest)(nil), "protos.SyncMapRequest")
	proto.RegisterType((*SyncMapReply)(nil), "protos.SyncMapReply")
	proto.RegisterType((*MigrateGetRequest)(nil), "protos.MigrateGetRequest")
	proto.RegisterType((*MigrateGetReply)(nil), "protos.MigrateGetReply")
	proto.RegisterType((*CreatePgRequest)(nil), "protos.CreatePgRequest")
	proto.RegisterType((*CreatePgReply)(nil), "protos.CreatePgReply")
	proto.RegisterType((*DeletePgRequest)(nil), "protos.DeletePgRequest")
	proto.RegisterType((*DeletePgReply)(nil), "protos.DeletePgReply")
	proto.RegisterEnum("protos.SyncMapType", SyncMapType_name, SyncMapType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OsdRpc service

type OsdRpcClient interface {
	CreatePg(ctx context.Context, in *CreatePgRequest, opts ...grpc.CallOption) (*CreatePgReply, error)
	DeletePg(ctx context.Context, in *DeletePgRequest, opts ...grpc.CallOption) (*DeletePgReply, error)
	SyncMap(ctx context.Context, in *SyncMapRequest, opts ...grpc.CallOption) (*SyncMapReply, error)
	MigrateGet(ctx context.Context, in *MigrateGetRequest, opts ...grpc.CallOption) (*MigrateGetReply, error)
}

type osdRpcClient struct {
	cc *grpc.ClientConn
}

func NewOsdRpcClient(cc *grpc.ClientConn) OsdRpcClient {
	return &osdRpcClient{cc}
}

func (c *osdRpcClient) CreatePg(ctx context.Context, in *CreatePgRequest, opts ...grpc.CallOption) (*CreatePgReply, error) {
	out := new(CreatePgReply)
	err := grpc.Invoke(ctx, "/protos.OsdRpc/CreatePg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osdRpcClient) DeletePg(ctx context.Context, in *DeletePgRequest, opts ...grpc.CallOption) (*DeletePgReply, error) {
	out := new(DeletePgReply)
	err := grpc.Invoke(ctx, "/protos.OsdRpc/DeletePg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osdRpcClient) SyncMap(ctx context.Context, in *SyncMapRequest, opts ...grpc.CallOption) (*SyncMapReply, error) {
	out := new(SyncMapReply)
	err := grpc.Invoke(ctx, "/protos.OsdRpc/SyncMap", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osdRpcClient) MigrateGet(ctx context.Context, in *MigrateGetRequest, opts ...grpc.CallOption) (*MigrateGetReply, error) {
	out := new(MigrateGetReply)
	err := grpc.Invoke(ctx, "/protos.OsdRpc/MigrateGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OsdRpc service

type OsdRpcServer interface {
	CreatePg(context.Context, *CreatePgRequest) (*CreatePgReply, error)
	DeletePg(context.Context, *DeletePgRequest) (*DeletePgReply, error)
	SyncMap(context.Context, *SyncMapRequest) (*SyncMapReply, error)
	MigrateGet(context.Context, *MigrateGetRequest) (*MigrateGetReply, error)
}

func RegisterOsdRpcServer(s *grpc.Server, srv OsdRpcServer) {
	s.RegisterService(&_OsdRpc_serviceDesc, srv)
}

func _OsdRpc_CreatePg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsdRpcServer).CreatePg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OsdRpc/CreatePg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsdRpcServer).CreatePg(ctx, req.(*CreatePgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsdRpc_DeletePg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsdRpcServer).DeletePg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OsdRpc/DeletePg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsdRpcServer).DeletePg(ctx, req.(*DeletePgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsdRpc_SyncMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsdRpcServer).SyncMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OsdRpc/SyncMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsdRpcServer).SyncMap(ctx, req.(*SyncMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsdRpc_MigrateGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsdRpcServer).MigrateGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OsdRpc/MigrateGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsdRpcServer).MigrateGet(ctx, req.(*MigrateGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OsdRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.OsdRpc",
	HandlerType: (*OsdRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePg",
			Handler:    _OsdRpc_CreatePg_Handler,
		},
		{
			MethodName: "DeletePg",
			Handler:    _OsdRpc_DeletePg_Handler,
		},
		{
			MethodName: "SyncMap",
			Handler:    _OsdRpc_SyncMap_Handler,
		},
		{
			MethodName: "MigrateGet",
			Handler:    _OsdRpc_MigrateGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osd.proto",
}

func (m *UnionMap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnionMap) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Pgmap != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.Pgmap.Size()))
		n1, err := m.Pgmap.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Poolmap != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.Poolmap.Size()))
		n2, err := m.Poolmap.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Osdmap != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.Osdmap.Size()))
		n3, err := m.Osdmap.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *SyncMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncMapRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MapType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.MapType))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintOsd(dAtA, i, uint64(m.UnionMap.Size()))
	n4, err := m.UnionMap.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	return i, nil
}

func (m *SyncMapReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncMapReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RetCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.RetCode))
	}
	return i, nil
}

func (m *MigrateGetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MigrateGetRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ParentPgId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.ParentPgId)))
		i += copy(dAtA[i:], m.ParentPgId)
	}
	if len(m.ChildPgId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.ChildPgId)))
		i += copy(dAtA[i:], m.ChildPgId)
	}
	if len(m.Marker) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.Marker)))
		i += copy(dAtA[i:], m.Marker)
	}
	return i, nil
}

func (m *MigrateGetReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MigrateGetReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	if len(m.Value) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.Value)))
		i += copy(dAtA[i:], m.Value)
	}
	if len(m.Marker) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.Marker)))
		i += copy(dAtA[i:], m.Marker)
	}
	return i, nil
}

func (m *CreatePgRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePgRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PgName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.PgName)))
		i += copy(dAtA[i:], m.PgName)
	}
	if m.GroupDescriptor != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.GroupDescriptor.Size()))
		n5, err := m.GroupDescriptor.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *CreatePgReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePgReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RetCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.RetCode))
	}
	return i, nil
}

func (m *DeletePgRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePgRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PgName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.PgName)))
		i += copy(dAtA[i:], m.PgName)
	}
	return i, nil
}

func (m *DeletePgReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePgReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RetCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.RetCode))
	}
	return i, nil
}

func encodeFixed64Osd(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Osd(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintOsd(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UnionMap) Size() (n int) {
	var l int
	_ = l
	if m.Pgmap != nil {
		l = m.Pgmap.Size()
		n += 1 + l + sovOsd(uint64(l))
	}
	if m.Poolmap != nil {
		l = m.Poolmap.Size()
		n += 1 + l + sovOsd(uint64(l))
	}
	if m.Osdmap != nil {
		l = m.Osdmap.Size()
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *SyncMapRequest) Size() (n int) {
	var l int
	_ = l
	if m.MapType != 0 {
		n += 1 + sovOsd(uint64(m.MapType))
	}
	l = m.UnionMap.Size()
	n += 1 + l + sovOsd(uint64(l))
	return n
}

func (m *SyncMapReply) Size() (n int) {
	var l int
	_ = l
	if m.RetCode != 0 {
		n += 1 + sovOsd(uint64(m.RetCode))
	}
	return n
}

func (m *MigrateGetRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ParentPgId)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	l = len(m.ChildPgId)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	l = len(m.Marker)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *MigrateGetReply) Size() (n int) {
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	l = len(m.Marker)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *CreatePgRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.PgName)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	if m.GroupDescriptor != nil {
		l = m.GroupDescriptor.Size()
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *CreatePgReply) Size() (n int) {
	var l int
	_ = l
	if m.RetCode != 0 {
		n += 1 + sovOsd(uint64(m.RetCode))
	}
	return n
}

func (m *DeletePgRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.PgName)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *DeletePgReply) Size() (n int) {
	var l int
	_ = l
	if m.RetCode != 0 {
		n += 1 + sovOsd(uint64(m.RetCode))
	}
	return n
}

func sovOsd(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOsd(x uint64) (n int) {
	return sovOsd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *UnionMap) GetValue() interface{} {
	if this.Pgmap != nil {
		return this.Pgmap
	}
	if this.Poolmap != nil {
		return this.Poolmap
	}
	if this.Osdmap != nil {
		return this.Osdmap
	}
	return nil
}

func (this *UnionMap) SetValue(value interface{}) bool {
	switch vt := value.(type) {
	case *PgMaps:
		this.Pgmap = vt
	case *PoolMap:
		this.Poolmap = vt
	case *OsdMap:
		this.Osdmap = vt
	default:
		return false
	}
	return true
}
func (m *UnionMap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnionMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnionMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pgmap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pgmap == nil {
				m.Pgmap = &PgMaps{}
			}
			if err := m.Pgmap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poolmap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Poolmap == nil {
				m.Poolmap = &PoolMap{}
			}
			if err := m.Poolmap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Osdmap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Osdmap == nil {
				m.Osdmap = &OsdMap{}
			}
			if err := m.Osdmap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapType", wireType)
			}
			m.MapType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MapType |= (SyncMapType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnionMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnionMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncMapReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncMapReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncMapReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetCode", wireType)
			}
			m.RetCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MigrateGetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MigrateGetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MigrateGetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentPgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentPgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChildPgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChildPgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Marker", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Marker = append(m.Marker[:0], dAtA[iNdEx:postIndex]...)
			if m.Marker == nil {
				m.Marker = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MigrateGetReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MigrateGetReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MigrateGetReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Marker", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Marker = append(m.Marker[:0], dAtA[iNdEx:postIndex]...)
			if m.Marker == nil {
				m.Marker = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePgRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePgRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePgRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PgName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupDescriptor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GroupDescriptor == nil {
				m.GroupDescriptor = &multiraftbase.GroupDescriptor{}
			}
			if err := m.GroupDescriptor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePgReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePgReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePgReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetCode", wireType)
			}
			m.RetCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePgRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePgRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePgRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PgName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePgReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePgReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePgReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetCode", wireType)
			}
			m.RetCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOsd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthOsd
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOsd
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOsd(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOsd = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOsd   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("osd.proto", fileDescriptorOsd) }

var fileDescriptorOsd = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xd3, 0xe6, 0x6f, 0x12, 0x9a, 0xb0, 0x94, 0x96, 0xe6, 0xe0, 0x56, 0x16, 0x42, 0xb4,
	0x87, 0x44, 0x6a, 0x0f, 0x08, 0xc4, 0x85, 0x36, 0x52, 0x55, 0x89, 0x90, 0xe0, 0xc2, 0xd9, 0xda,
	0x66, 0x87, 0xad, 0xa9, 0xed, 0x5d, 0xd6, 0x6b, 0x24, 0x9f, 0xb9, 0xc0, 0x1b, 0x70, 0x44, 0xe2,
	0x65, 0x7a, 0xe4, 0x09, 0x10, 0x2a, 0x2f, 0x82, 0xd6, 0x3f, 0x4d, 0xd3, 0xf2, 0x77, 0xca, 0xec,
	0xcc, 0xf7, 0x7d, 0xf3, 0xcd, 0x68, 0x62, 0x68, 0x89, 0x98, 0x0d, 0xa4, 0x12, 0x5a, 0x90, 0x7a,
	0xf6, 0x13, 0xf7, 0x47, 0xdc, 0xd7, 0xa7, 0xc9, 0xc9, 0x60, 0x26, 0xc2, 0xe1, 0x5b, 0x91, 0xa8,
	0x08, 0xd3, 0xd0, 0x67, 0x91, 0xcf, 0x4f, 0xf5, 0x30, 0xc2, 0x48, 0x2b, 0x21, 0xd3, 0xa1, 0x88,
	0xd9, 0x30, 0x4c, 0x02, 0xed, 0x2b, 0xfa, 0x46, 0x9f, 0xd0, 0x18, 0x87, 0x21, 0x6a, 0xca, 0xa8,
	0xa6, 0xb9, 0x5a, 0xbf, 0x15, 0x8a, 0xa8, 0x08, 0x57, 0xb9, 0xe0, 0x22, 0x0b, 0x87, 0x26, 0xca,
	0xb3, 0xce, 0x27, 0x0b, 0x9a, 0xaf, 0x23, 0x5f, 0x44, 0x63, 0x2a, 0xc9, 0x7d, 0xa8, 0x49, 0x1e,
	0x52, 0x79, 0xcf, 0xda, 0xb2, 0x1e, 0xb6, 0x77, 0x57, 0x72, 0x4c, 0x3c, 0x98, 0xf2, 0x31, 0x95,
	0xb1, 0x9b, 0x17, 0xc9, 0x36, 0x34, 0xa4, 0x10, 0x81, 0xc1, 0x55, 0x33, 0x5c, 0xf7, 0x12, 0x27,
	0x44, 0x30, 0xa6, 0xd2, 0x2d, 0xeb, 0xe4, 0x01, 0xd4, 0x45, 0xcc, 0x0c, 0x72, 0x69, 0x51, 0x71,
	0x12, 0x33, 0x03, 0x2c, 0xaa, 0x4f, 0x96, 0xcf, 0xbf, 0x6c, 0x5a, 0x4e, 0x02, 0x2b, 0xc7, 0x69,
	0x34, 0x33, 0x05, 0x7c, 0x97, 0x60, 0xac, 0xc9, 0x00, 0x9a, 0x21, 0x95, 0x9e, 0x4e, 0x25, 0x66,
	0x9e, 0x56, 0x76, 0xef, 0x94, 0x0a, 0x05, 0xf2, 0x55, 0x2a, 0xd1, 0x6d, 0x84, 0x79, 0x40, 0xf6,
	0xa0, 0x95, 0x98, 0x61, 0xbc, 0xb9, 0xb9, 0x5e, 0x49, 0x28, 0xa7, 0xdc, 0x5f, 0x3e, 0xff, 0xbe,
	0x59, 0x71, 0x9b, 0x49, 0xf1, 0x76, 0xb6, 0xa1, 0x73, 0xd9, 0x56, 0x06, 0x29, 0xd9, 0x80, 0xa6,
	0x42, 0xed, 0xcd, 0x04, 0xcb, 0x9b, 0xd6, 0xdc, 0x86, 0x42, 0x7d, 0x20, 0x18, 0x3a, 0x21, 0xdc,
	0x1e, 0xfb, 0x5c, 0x51, 0x8d, 0x87, 0xa8, 0x4b, 0x93, 0x5b, 0xd0, 0x91, 0x54, 0x61, 0xa4, 0x3d,
	0xc9, 0x3d, 0x9f, 0x65, 0x9c, 0x96, 0x0b, 0x79, 0x6e, 0xca, 0x8f, 0x18, 0xb1, 0xa1, 0x3d, 0x3b,
	0xf5, 0x03, 0x56, 0x00, 0xaa, 0x19, 0xa0, 0x95, 0xa5, 0xb2, 0xfa, 0x1a, 0xd4, 0x43, 0xaa, 0xce,
	0x50, 0x65, 0x6b, 0xea, 0xb8, 0xc5, 0xcb, 0x79, 0x09, 0xdd, 0xab, 0xed, 0x8c, 0xb9, 0x1e, 0x2c,
	0x9d, 0x61, 0x9a, 0xf5, 0xe8, 0xb8, 0x26, 0x24, 0xab, 0x50, 0x7b, 0x4f, 0x83, 0x04, 0x33, 0xd9,
	0x8e, 0x9b, 0x3f, 0xfe, 0x28, 0x99, 0x40, 0xf7, 0x40, 0x21, 0xd5, 0x38, 0xe5, 0xa5, 0xff, 0x75,
	0x68, 0x48, 0xee, 0x45, 0x34, 0xc4, 0xc2, 0x7a, 0x5d, 0xf2, 0x17, 0x34, 0x44, 0x72, 0x04, 0x3d,
	0xae, 0x44, 0x22, 0x3d, 0x86, 0xf1, 0x4c, 0xf9, 0x52, 0x0b, 0x55, 0x2c, 0xd5, 0x1e, 0x2c, 0x5c,
	0xdd, 0xe0, 0xd0, 0xc0, 0x46, 0x97, 0x28, 0xb7, 0xcb, 0x17, 0x13, 0xce, 0x0e, 0xdc, 0x9a, 0xb7,
	0xfd, 0xc7, 0x92, 0x77, 0xa0, 0x3b, 0xc2, 0x00, 0xff, 0xc7, 0xa2, 0xd1, 0x9d, 0x63, 0xff, 0xae,
	0xbb, 0xf3, 0x08, 0xda, 0x57, 0x8e, 0x86, 0xb4, 0xa0, 0x36, 0x3d, 0x1c, 0x3f, 0x9b, 0xf6, 0x2a,
	0x04, 0xa0, 0x3e, 0x39, 0x1e, 0x99, 0xd8, 0x22, 0x6d, 0x68, 0x4c, 0x27, 0x93, 0xe7, 0xe6, 0x51,
	0xed, 0x2f, 0x7f, 0xfc, 0x6a, 0x57, 0x76, 0x3f, 0x54, 0xa1, 0x3e, 0x89, 0x99, 0x2b, 0x67, 0xe4,
	0x29, 0x34, 0xcb, 0x39, 0xc8, 0x7a, 0x79, 0x59, 0xd7, 0x16, 0xda, 0xbf, 0x7b, 0xb3, 0x20, 0x83,
	0xd4, 0xa9, 0x18, 0x76, 0xe9, 0x76, 0xce, 0xbe, 0x36, 0xeb, 0x9c, 0xbd, 0x30, 0x98, 0x53, 0x21,
	0x8f, 0xa1, 0x51, 0xf8, 0x27, 0x6b, 0xd7, 0xfe, 0x05, 0x25, 0x77, 0xf5, 0x46, 0x3e, 0xa7, 0xee,
	0x03, 0xcc, 0x0f, 0x89, 0x6c, 0x94, 0xa8, 0x1b, 0xb7, 0xdc, 0x5f, 0xff, 0x5d, 0x29, 0xd3, 0xd8,
	0xef, 0x9d, 0x5f, 0xd8, 0xd6, 0xb7, 0x0b, 0xdb, 0xfa, 0x71, 0x61, 0x5b, 0x9f, 0x7f, 0xda, 0x95,
	0x93, 0xfc, 0x53, 0xb5, 0xf7, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc8, 0x2f, 0x7f, 0xbe, 0x04,
	0x00, 0x00,
}
