// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osd.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import multiraftbase "github.com/journeymidnight/nentropy/multiraft/multiraftbase"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreatePgRequest struct {
	PgName          string                         `protobuf:"bytes,1,opt,name=pg_name,json=pgName,proto3" json:"pg_name,omitempty"`
	GroupDescriptor *multiraftbase.GroupDescriptor `protobuf:"bytes,2,opt,name=group_descriptor,json=groupDescriptor" json:"group_descriptor,omitempty"`
}

func (m *CreatePgRequest) Reset()                    { *m = CreatePgRequest{} }
func (m *CreatePgRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePgRequest) ProtoMessage()               {}
func (*CreatePgRequest) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{0} }

func (m *CreatePgRequest) GetPgName() string {
	if m != nil {
		return m.PgName
	}
	return ""
}

func (m *CreatePgRequest) GetGroupDescriptor() *multiraftbase.GroupDescriptor {
	if m != nil {
		return m.GroupDescriptor
	}
	return nil
}

type CreatePgReply struct {
	RetCode int32 `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
}

func (m *CreatePgReply) Reset()                    { *m = CreatePgReply{} }
func (m *CreatePgReply) String() string            { return proto.CompactTextString(m) }
func (*CreatePgReply) ProtoMessage()               {}
func (*CreatePgReply) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{1} }

func (m *CreatePgReply) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type DeletePgRequest struct {
	PgName string `protobuf:"bytes,1,opt,name=pg_name,json=pgName,proto3" json:"pg_name,omitempty"`
}

func (m *DeletePgRequest) Reset()                    { *m = DeletePgRequest{} }
func (m *DeletePgRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePgRequest) ProtoMessage()               {}
func (*DeletePgRequest) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{2} }

func (m *DeletePgRequest) GetPgName() string {
	if m != nil {
		return m.PgName
	}
	return ""
}

type DeletePgReply struct {
	RetCode int32 `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
}

func (m *DeletePgReply) Reset()                    { *m = DeletePgReply{} }
func (m *DeletePgReply) String() string            { return proto.CompactTextString(m) }
func (*DeletePgReply) ProtoMessage()               {}
func (*DeletePgReply) Descriptor() ([]byte, []int) { return fileDescriptorOsd, []int{3} }

func (m *DeletePgReply) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*CreatePgRequest)(nil), "protos.CreatePgRequest")
	proto.RegisterType((*CreatePgReply)(nil), "protos.CreatePgReply")
	proto.RegisterType((*DeletePgRequest)(nil), "protos.DeletePgRequest")
	proto.RegisterType((*DeletePgReply)(nil), "protos.DeletePgReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OsdRpc service

type OsdRpcClient interface {
	CreatePg(ctx context.Context, in *CreatePgRequest, opts ...grpc.CallOption) (*CreatePgReply, error)
	DeletePg(ctx context.Context, in *DeletePgRequest, opts ...grpc.CallOption) (*DeletePgReply, error)
}

type osdRpcClient struct {
	cc *grpc.ClientConn
}

func NewOsdRpcClient(cc *grpc.ClientConn) OsdRpcClient {
	return &osdRpcClient{cc}
}

func (c *osdRpcClient) CreatePg(ctx context.Context, in *CreatePgRequest, opts ...grpc.CallOption) (*CreatePgReply, error) {
	out := new(CreatePgReply)
	err := grpc.Invoke(ctx, "/protos.OsdRpc/CreatePg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osdRpcClient) DeletePg(ctx context.Context, in *DeletePgRequest, opts ...grpc.CallOption) (*DeletePgReply, error) {
	out := new(DeletePgReply)
	err := grpc.Invoke(ctx, "/protos.OsdRpc/DeletePg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OsdRpc service

type OsdRpcServer interface {
	CreatePg(context.Context, *CreatePgRequest) (*CreatePgReply, error)
	DeletePg(context.Context, *DeletePgRequest) (*DeletePgReply, error)
}

func RegisterOsdRpcServer(s *grpc.Server, srv OsdRpcServer) {
	s.RegisterService(&_OsdRpc_serviceDesc, srv)
}

func _OsdRpc_CreatePg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsdRpcServer).CreatePg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OsdRpc/CreatePg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsdRpcServer).CreatePg(ctx, req.(*CreatePgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsdRpc_DeletePg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsdRpcServer).DeletePg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OsdRpc/DeletePg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsdRpcServer).DeletePg(ctx, req.(*DeletePgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OsdRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.OsdRpc",
	HandlerType: (*OsdRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePg",
			Handler:    _OsdRpc_CreatePg_Handler,
		},
		{
			MethodName: "DeletePg",
			Handler:    _OsdRpc_DeletePg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osd.proto",
}

func (m *CreatePgRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePgRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PgName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.PgName)))
		i += copy(dAtA[i:], m.PgName)
	}
	if m.GroupDescriptor != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.GroupDescriptor.Size()))
		n1, err := m.GroupDescriptor.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *CreatePgReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePgReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RetCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.RetCode))
	}
	return i, nil
}

func (m *DeletePgRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePgRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PgName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOsd(dAtA, i, uint64(len(m.PgName)))
		i += copy(dAtA[i:], m.PgName)
	}
	return i, nil
}

func (m *DeletePgReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePgReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RetCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintOsd(dAtA, i, uint64(m.RetCode))
	}
	return i, nil
}

func encodeFixed64Osd(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Osd(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintOsd(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CreatePgRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.PgName)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	if m.GroupDescriptor != nil {
		l = m.GroupDescriptor.Size()
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *CreatePgReply) Size() (n int) {
	var l int
	_ = l
	if m.RetCode != 0 {
		n += 1 + sovOsd(uint64(m.RetCode))
	}
	return n
}

func (m *DeletePgRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.PgName)
	if l > 0 {
		n += 1 + l + sovOsd(uint64(l))
	}
	return n
}

func (m *DeletePgReply) Size() (n int) {
	var l int
	_ = l
	if m.RetCode != 0 {
		n += 1 + sovOsd(uint64(m.RetCode))
	}
	return n
}

func sovOsd(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOsd(x uint64) (n int) {
	return sovOsd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreatePgRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePgRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePgRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PgName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupDescriptor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GroupDescriptor == nil {
				m.GroupDescriptor = &multiraftbase.GroupDescriptor{}
			}
			if err := m.GroupDescriptor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePgReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePgReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePgReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetCode", wireType)
			}
			m.RetCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePgRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePgRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePgRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOsd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PgName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePgReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePgReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePgReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetCode", wireType)
			}
			m.RetCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOsd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOsd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOsd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOsd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOsd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthOsd
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOsd
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOsd(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOsd = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOsd   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("osd.proto", fileDescriptorOsd) }

var fileDescriptorOsd = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4d, 0x4a, 0x03, 0x31,
	0x14, 0xc7, 0x1b, 0xc1, 0x7e, 0x44, 0xa4, 0x25, 0x20, 0xad, 0x5d, 0x0c, 0x65, 0x56, 0xa5, 0x8b,
	0x19, 0xa8, 0x5b, 0x57, 0xb6, 0x20, 0xba, 0x50, 0x99, 0x0b, 0x94, 0x74, 0xf2, 0x4c, 0x47, 0x26,
	0x93, 0x98, 0xbc, 0x2c, 0x66, 0xef, 0x21, 0x3c, 0x92, 0x4b, 0x8f, 0x20, 0xf5, 0x22, 0x52, 0x87,
	0x3a, 0x4c, 0x05, 0x71, 0x95, 0x90, 0xfc, 0x3f, 0x7e, 0xbc, 0x47, 0x7b, 0xda, 0x89, 0xc8, 0x58,
	0x8d, 0x9a, 0xb5, 0xbf, 0x0f, 0x37, 0xbe, 0x95, 0x19, 0x6e, 0xfc, 0x3a, 0x4a, 0xb5, 0x8a, 0x9f,
	0xb4, 0xb7, 0x05, 0x94, 0x2a, 0x13, 0x45, 0x26, 0x37, 0x18, 0x17, 0x50, 0xa0, 0xd5, 0xa6, 0x8c,
	0x95, 0xcf, 0x31, 0xb3, 0xfc, 0x11, 0xeb, 0xdb, 0x9a, 0x3b, 0x88, 0x15, 0x20, 0x17, 0x1c, 0x79,
	0x95, 0x19, 0x7a, 0xda, 0x5f, 0x58, 0xe0, 0x08, 0x0f, 0x32, 0x81, 0x67, 0x0f, 0x0e, 0xd9, 0x90,
	0x76, 0x8c, 0x5c, 0x15, 0x5c, 0xc1, 0x88, 0x4c, 0xc8, 0xb4, 0x97, 0xb4, 0x8d, 0xbc, 0xe3, 0x0a,
	0xd8, 0x0d, 0x1d, 0x48, 0xab, 0xbd, 0x59, 0x09, 0x70, 0xa9, 0xcd, 0x0c, 0x6a, 0x3b, 0x3a, 0x9a,
	0x90, 0xe9, 0xc9, 0x3c, 0x88, 0x1a, 0x25, 0xd1, 0xf5, 0x4e, 0xb6, 0xfc, 0x51, 0x25, 0x7d, 0xd9,
	0x7c, 0x08, 0x67, 0xf4, 0xb4, 0xae, 0x35, 0x79, 0xc9, 0xce, 0x69, 0xd7, 0x02, 0xae, 0x52, 0x2d,
	0xaa, 0xd6, 0xe3, 0xa4, 0x63, 0x01, 0x17, 0x5a, 0x40, 0x38, 0xa3, 0xfd, 0x25, 0xe4, 0xf0, 0x1f,
	0xc4, 0x5d, 0x6e, 0xad, 0xfd, 0x3b, 0x77, 0xfe, 0x42, 0x68, 0xfb, 0xde, 0x89, 0xc4, 0xa4, 0xec,
	0x92, 0x76, 0xf7, 0x38, 0x6c, 0x58, 0x4d, 0xc6, 0x45, 0x07, 0x73, 0x19, 0x9f, 0xfd, 0xfe, 0x30,
	0x79, 0x19, 0xb6, 0x76, 0xee, 0x7d, 0x69, 0xed, 0x3e, 0x40, 0xae, 0xdd, 0x0d, 0xbe, 0xb0, 0x75,
	0x35, 0x78, 0xdb, 0x06, 0xe4, 0x7d, 0x1b, 0x90, 0x8f, 0x6d, 0x40, 0x5e, 0x3f, 0x83, 0xd6, 0xba,
	0xda, 0xf3, 0xc5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x1f, 0x1d, 0xc7, 0xfb, 0x01, 0x00,
	0x00,
}
